final commit
harshpatel-javascript/React-practicals pull request #10
Opened 2022-03-25 09:31 UTC by harshpatel-javascript

2022-03-25 10:07 UTC, Rutvi25 requested changes

2022-03-25 10:07 UTC, Rutvi25 commented on practical-6/src/css/Card.css
> +  top: 5rem;
use px instead of rem

2022-03-25 10:07 UTC, Rutvi25 commented on practical-6/src/css/UserContainer.css
> +  background-color: white;
use hexcode

2022-03-25 10:07 UTC, Rutvi25 commented on practical-6/src/index.css
> +  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "Roboto", "Oxygen",
unused fonts can be removed

2022-03-28 06:21 UTC, Rutvi25 approved these changes

2022-03-28 13:57 UTC, desaianiruddh approved these changes

2022-03-29 03:34 UTC, Rutvi25 approved these changes

2022-03-29 06:24 UTC, sheth-jay requested changes

2022-04-01 05:00 UTC, sheth-jay approved these changes

2022-04-01 05:01 UTC, merged