practical-8
harshpatel-javascript/React-practicals pull request #13
Opened 2022-04-06 09:29 UTC by harshpatel-javascript

2022-04-06 10:09 UTC, Rutvi25 requested changes

2022-04-06 10:09 UTC, Rutvi25 commented on practical-8/src/components/Signup.js
> +    isEyeOpen ? setIsEyeOpen(false) : setIsEyeOpen(true);
hidePassword or showPassword can be used instead of isEyeOpen

2022-04-06 10:09 UTC, Rutvi25 commented on practical-8/src/index.css
> +  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "Roboto", "Oxygen",
unused fonts can be removed

2022-04-06 10:09 UTC, Rutvi25 commented on practical-8/src/redux/reducer.js
> +  switch (action.type) {
destructure can be done

2022-04-06 10:09 UTC, Rutvi25 commented on practical-8/src/redux/store.js
> +import { reducer } from "./reducer";
keep a line gap between global and local imports

2022-04-06 10:09 UTC, Rutvi25 commented on practical-8/src/components/Signup.js
> +              onBlur={formik.handleBlur}
Field & ErrorMessage Components can be used

2022-04-06 10:13 UTC, Rutvi25 commented on practical-8/src/components/Signup.js
> +            <input
Field & ErrorMessage Components can be used

2022-04-06 10:39 UTC, harshpatel-javascript commented on practical-8/src/components/Signup.js
> +            <input
I've used the useFormik hook so with that Errormesage can't be used.
 [you can check here](https://formik.org/docs/api/useFormik)

2022-04-06 11:06 UTC, Rutvi25 approved these changes

2022-04-07 05:07 UTC, desaianiruddh commented on practical-8/src/components/Home.js
> +function Home() {
use arrow function if possible

2022-04-07 05:07 UTC, desaianiruddh commented on practical-8/src/components/Home.js
> +function Home() {
use arrow function if possible

2022-04-07 05:09 UTC, desaianiruddh commented on practical-8/src/components/Home.js
> +            <img src={userData.fileUrl} alt="Uploaded file" />
destructure useData's property

2022-04-07 05:09 UTC, desaianiruddh commented on practical-8/src/components/Home.js
> +            <img src={userData.fileUrl} alt="Uploaded file" />
destructure useData's property

2022-04-07 05:13 UTC, desaianiruddh commented on practical-8/src/components/Signup.js
> +    errors.name = "It is too less than the required length";
write appropriate error message. so user can understand what actually needs to enter in field

2022-04-07 05:13 UTC, desaianiruddh commented on practical-8/src/components/Signup.js
> +    errors.name = "It is too less than the required length";
write appropriate error message. so user can understand what actually needs to enter in field

2022-04-07 05:16 UTC, desaianiruddh commented on practical-8/src/components/Signup.js
> +    errors.confirmPassword = "This field is not same as Password";
instead of this field use confirm password..

2022-04-07 05:16 UTC, desaianiruddh commented on practical-8/src/components/Signup.js
> +    errors.confirmPassword = "This field is not same as Password";
instead of this field use confirm password..

2022-04-07 05:20 UTC, desaianiruddh commented on practical-8/src/components/Signup.js
> +            <></>
use && instead of ? : so you have to only render one condition

2022-04-07 05:20 UTC, desaianiruddh commented on practical-8/src/components/Signup.js
> +            <></>
use && instead of ? : so you have to only render one condition

2022-04-07 05:20 UTC, desaianiruddh commented on practical-8/src/components/Signup.js
> +            {isImageUploaded ? (
use &&

2022-04-07 05:20 UTC, desaianiruddh commented on practical-8/src/components/Signup.js
> +            {isImageUploaded ? (
use &&

2022-04-07 05:21 UTC, desaianiruddh commented on practical-8/src/components/Signup.js
> +            {formik.touched.file && formik.errors.file ? (
use && so you will no need to add : null

2022-04-07 13:30 UTC, desaianiruddh approved these changes

2022-04-08 09:35 UTC, sheth-jay approved these changes

2022-04-11 11:02 UTC, merged