Practical 6
harshpatel-javascript/React-practicals pull request #7
Opened 2022-03-17 11:49 UTC by harshpatel-javascript

2022-03-22 10:13 UTC, desaianiruddh commented on Practical-6/src/components/UserList.js
> +      {data.access === "Owner" ? (
you should set conditional rendering 
data.access === "Owner" 
? first element
: second element

2022-03-22 10:19 UTC, desaianiruddh commented on Practical-6/src/css/UserContainer.css
> +  padding: 1rem 2rem;
use px instead of rem if all other place you are using px

2022-03-22 10:21 UTC, desaianiruddh commented on Practical-6/src/index.css
> +code {
remove code css-class which is came with CRA if there's no need

2022-03-22 10:26 UTC, desaianiruddh commented on Practical-6/src/redux/reducer.js
> +  definedData: userData,
Data is not defined. we are getting dynamic data from API server. you should change name of property

2022-03-22 10:34 UTC, desaianiruddh commented on Practical-6/src/redux/reducer.js
> +        definedData: userData,
use copy of previous state and modify that.
definedData is constant no need to re-write
return {
        ...state,
        cardData: action.payload
};

2022-03-22 10:52 UTC, desaianiruddh commented on Practical-6/src/components/UserList.js
> +      {data.status === "Active" ? (
you should set conditional rendering like below,
data.access === "Owner"
? first element
: second element

2022-03-22 12:42 UTC, desaianiruddh commented on Practical-6/src/components/UserList.js
> +import {
put blank line between internal and external lib.

2022-03-23 07:05 UTC, Rutvi25 requested changes

2022-03-23 07:05 UTC, Rutvi25 commented on Practical-6/src/components/UserList.js
> +  const clickHandler = () => {
naming convention could be more relevant like deleteHandler instead of clickHandler

2022-03-23 10:38 UTC, desaianiruddh approved these changes

2022-03-23 11:00 UTC, Rutvi25 approved these changes

2022-03-25 09:05 UTC, closed without merging